import vcf with external calculation and no gt -1
labsquare/cutevariant pull request #370
Opened 2022-04-09 21:39 UTC by antonylebechec

Import VCF improvement.
Variant count and freq calculation externalized (without triggers)
Remove -1 genotype

2022-04-09 22:19 UTC, dridk requested changes
qque modif ! Pas encore regardé les trigger attentivement

2022-04-09 22:19 UTC, dridk commented on cutevariant/core/sql.py
> +        "description": "Number of samples",
nombre de samples de koi?

2022-04-09 22:19 UTC, dridk commented on cutevariant/core/sql.py
> +                        query_remove = f"""DELETE FROM sample_has_variant WHERE variant_id={sample["variant_id"]} AND sample_id={sample["sample_id"]}"""
Ce serait mieux de ne pas l'inserer directement au lieu de le supprimer ?

2022-04-09 22:19 UTC, dridk commented on cutevariant/core/sql.py
> +                        query = f"INSERT OR REPLACE INTO sample_has_variant ({query_fields}) VALUES ({query_values})"
Cette ligne, ne pas l'executer si gt = -1

2022-04-09 22:19 UTC, dridk commented on cutevariant/core/sql.py
> +    """Insert many variants from data into variants table
Tu peux préciser ce que fait la fonction ? Pas compris .

2022-04-09 22:20 UTC, dridk commented
y a un soucis avec les tests aussi

2022-04-10 00:36 UTC, antonylebechec commented
J'ai fait un autre fix ! 
Un problème dans le calcul des count et nb_samples sur les phenotype case/control.
C'est réglé avec 2 triggers à la place d'un. Par contre, il sont badass les triggers... j'ai testé sur du gros VCF, je vais voir sur du plus gros VCF (chr1)

2022-04-10 00:37 UTC, antonylebechec commented
Pour les test, j'ai vu que ça ne passait pas, mais je ne sais pas pourquoi...
Il y a des champs qui ont changé peut-être

2022-04-10 00:56 UTC, antonylebechec commented on cutevariant/core/sql.py
> +        "description": "Number of samples",
C'est un champ en plus pour chaque variant qui place le nombre de samples pour réaliser le calcul rapide avec un trigger. Sinon ça prend des plombes pour réaliser les calculs avec les triggers

2022-04-10 00:56 UTC, antonylebechec commented on cutevariant/core/sql.py
> +                        query_remove = f"""DELETE FROM sample_has_variant WHERE variant_id={sample["variant_id"]} AND sample_id={sample["sample_id"]}"""
C'est dans le cas d'une mise à jour lors de l'insertion d'un nouveau VCF, avec de nouveaux genotypes. SInon tu laisse le genotype et c'est pas bon

2022-04-10 00:56 UTC, antonylebechec commented on cutevariant/core/sql.py
> +                        query = f"INSERT OR REPLACE INTO sample_has_variant ({query_fields}) VALUES ({query_values})"
Oui, c'est le pourquoi du if

2022-04-10 00:56 UTC, antonylebechec commented on cutevariant/core/sql.py
> +                        query_remove = f"""DELETE FROM sample_has_variant WHERE variant_id={sample["variant_id"]} AND sample_id={sample["sample_id"]}"""
C'est dans le cas d'une mise à jour lors de l'insertion d'un nouveau VCF, avec de nouveaux genotypes. SInon tu laisse le genotype et c'est pas bon

2022-04-10 00:58 UTC, antonylebechec commented on cutevariant/core/sql.py
> +    """Insert many variants from data into variants table
Cette fonction calcul les count et freq pour chaque variant.
Elle remplace les triggers qui sont trop longs dans le cas d'insertion de beaucoup de données.
On ne fait donc qu'une seule fois le calcul, plutôt qu'à chaque fois qu'un gt est insert.

2022-04-10 01:23 UTC, antonylebechec commented
> 

Un test sur le VCF chr1 permet de dire que le changement de phenotype (case/control) active 2 triggers pour refaire les calculs en environ 10 secondes. C'est un peu long mais je trouve que ça passe. Le truc c'est que les triggers vont faire des INNER JOIN, et ça prend du temps quand on a beaucoup de variants...

2022-05-05 11:01 UTC, antonylebechec commented
PR à merge
En urgence !

2022-05-08 14:07 UTC, antonylebechec commented
issue #424 (Count number of validated genotype)
Local python3 -m pytest tests/core OK

2022-05-22 00:03 UTC, dridk commented
Fixé

2022-05-22 00:03 UTC, closed without merging