Added query list plugin
labsquare/cutevariant pull request #410
Opened 2022-04-25 20:36 UTC by SteampunkIslande

![example_query_list](https://user-images.githubusercontent.com/64743278/165170317-4627252f-3e63-4a5d-9eb8-acc1954f4de3.gif)

2022-04-25 20:38 UTC, SteampunkIslande commented
I had to choose, the description is in the UserRole, and the query in the ToolTipRole.
Only two critical line ranges regarding this:
lines 136-139
line 227

2022-04-26 07:24 UTC, dridk requested changes
- [x] Ca serait bien de pouvoir éditer une requete 
- [x] Les lignes plus large ( 20 px comme les autres ) 
- [x] Le tooltip affiche la description pas la requete. Pour voir la requete, faire "edit " .

2022-04-26 07:39 UTC, dridk requested changes

2022-04-26 07:39 UTC, dridk commented on cutevariant/gui/plugins/query_list/widgets.py
> +        if role == Qt.UserRole:
Inverser. Mettre la description sur tooltip

2022-04-26 07:39 UTC, dridk commented on cutevariant/gui/plugins/query_list/widgets.py
> +        query = self.model.data(index, Qt.ToolTipRole)
Inverser  : Qt.UserRole

2022-04-26 07:39 UTC, dridk commented on cutevariant/gui/plugins/query_list/widgets.py
> +
Crée la fonction _edit_query(self). 

- Ouvre une boite de dialog et met les infos de la ligne selectionné

2022-04-26 08:59 UTC, SteampunkIslande commented on cutevariant/gui/plugins/query_list/widgets.py
> +        if role == Qt.UserRole:
Fait

2022-04-26 08:59 UTC, SteampunkIslande commented on cutevariant/gui/plugins/query_list/widgets.py
> +        query = self.model.data(index, Qt.ToolTipRole)
Fait

2022-04-26 17:19 UTC, merged