issue #288 HAS operator with comma and &, some fix
labsquare/cutevariant pull request #413
Opened 2022-04-27 00:48 UTC by antonylebechec

issue #288 
Change HAS operator with standard VCF comma ','
Add HAS operator "HAS (with '&')" in "Filters editor"
Change CuteStyle for Tags
Change Tags separator in variant, sample and sample_variant widgets
Fix Tags add in variant, sample and sample_variant widgets (remove empty tag)

2022-04-28 12:02 UTC, dridk commented
- Ok pour changer le separateur 
- Pas ok pour le nouveau operateur : "HAS&"  ==> C'est trop bizarre gramaticallement .

2022-04-28 12:03 UTC, dridk commented on cutevariant/core/querybuilder.py
> +    "$nha&": "NOT HA&",
je trouve ça bizarre. Pk un cas particulier pour "&" ?
Laissons le choix à l'utilisateur de mettre ce qu'il veut. Par default la virgule.

2022-04-28 12:07 UTC, dridk requested changes

2022-04-28 12:07 UTC, dridk commented on cutevariant/core/querybuilder.py
> +        field = f"',' || {field} || ','"
- Créer une variable global "HAS_DELIMITER" dans common.py et utiliser cette variable au lieu de la "," en brute

2022-04-28 12:07 UTC, dridk commented on cutevariant/core/querybuilder.py
> +
A supprimer.

2022-04-28 12:07 UTC, dridk commented on cutevariant/gui/plugins/filters_editor/widgets.py
> +    "$nha&": "Has not (with '&')",
a supprimer

2022-04-28 12:07 UTC, dridk commented on cutevariant/gui/widgets/sample_variant_widget.py
> +        self.TAG_SEPARATOR = ","
récupérer depuis une variable global "common.HAS_SEPARATOR"

2022-04-28 13:50 UTC, antonylebechec commented
OK, je m'occupe de refaire cette partie

2022-04-28 14:27 UTC, antonylebechec commented
Fixes :
- cutevariant.commons.HAS_OPERATOR=","
- Variable dans le query builder et les widgets
- HA& enlevé dans le query builder, le plugin Filters et les tests 
- Fix de SAMPLE_CLASSIFICATION dans le widget sample_widget.py

Concernant les filtres sur des champs composés de listes avec d'autres séparateur que ",", on pourra toujours utiliser l'opérateur "Contains". Notamment pour les champs de snpEff :
```
SELECT favorite,classification,chr,pos,ref,alt,tags,ann.consequence FROM variants WHERE tags HAS '#test1' AND ann.consequence =~ 'intron_variant'
```
On pourra également simuler en SQL (donc pas directement dans le "VQL Editor" ni dans "Filters Editor") l'opérateur HAS avec un autre séparateur, pour des plugins particuliers (pour de la stat par exemple). Par exemple :
```
'&' || ann.consequence || '&' LIKE '%&intron_variant&%'
```
Ce n'est pas parfait, mais c'est raccord avec le format VCF.
Est-ce que le plugin "Query List" pourrait également proposer des requêtes directement en SQL ? Cela permettrait d'ouvrir à plus de possibilités...

2022-05-05 10:59 UTC, antonylebechec commented
PR a merge

2022-05-18 22:54 UTC, dridk commented
- Operator à mettre dans constant.py 
- Résoudre les confilts

2022-06-03 15:33 UTC, closed without merging